// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/storageref/storageref.proto

/*
Package storageref is a generated protocol buffer package.

It is generated from these files:
	github.com/aperturerobotics/storageref/storageref.proto

It has these top-level messages:
	StorageRef
	StorageRefIPFS
	StorageRefDigest
	StorageRefInBand
*/
package storageref

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StorageType contains the possible types of storage.
type StorageType int32

const (
	// StorageType_UNKNOWN holds unknown values.
	StorageType_StorageType_UNKNOWN StorageType = 0
	// StorageType_IPFS is the IPFS storage type.
	StorageType_StorageType_IPFS StorageType = 1
	// StorageType_DIGEST references a digest in local storage only by object multihash.
	StorageType_StorageType_DIGEST StorageType = 2
	// StorageType_INBAND stores object data in the storage reference itself, in-band.
	StorageType_StorageType_INBAND StorageType = 3
)

var StorageType_name = map[int32]string{
	0: "StorageType_UNKNOWN",
	1: "StorageType_IPFS",
	2: "StorageType_DIGEST",
	3: "StorageType_INBAND",
}
var StorageType_value = map[string]int32{
	"StorageType_UNKNOWN": 0,
	"StorageType_IPFS":    1,
	"StorageType_DIGEST":  2,
	"StorageType_INBAND":  3,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}
func (StorageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// IPFSRefType is an ipfs reference type.
type IPFSRefType int32

const (
	// IPFSRefType_BLOCK is the default reference type, an IPFS block.
	IPFSRefType_IPFSRefType_BLOCK IPFSRefType = 0
	// IPFSRefType_OBJECT indicates the hash refers to a IPFS merkle object.
	IPFSRefType_IPFSRefType_OBJECT IPFSRefType = 1
)

var IPFSRefType_name = map[int32]string{
	0: "IPFSRefType_BLOCK",
	1: "IPFSRefType_OBJECT",
}
var IPFSRefType_value = map[string]int32{
	"IPFSRefType_BLOCK":  0,
	"IPFSRefType_OBJECT": 1,
}

func (x IPFSRefType) String() string {
	return proto.EnumName(IPFSRefType_name, int32(x))
}
func (IPFSRefType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// StorageRef references storage.
type StorageRef struct {
	// StorageType contains the type of storage this references.
	StorageType StorageType `protobuf:"varint,1,opt,name=storage_type,json=storageType,enum=storageref.StorageType" json:"storage_type,omitempty"`
	// ObjectDigest contains the digest of the decrypted object.
	// Optional.
	ObjectDigest []byte `protobuf:"bytes,3,opt,name=object_digest,json=objectDigest,proto3" json:"object_digest,omitempty"`
	// Ipfs contains a IPFS storage reference.
	Ipfs *StorageRefIPFS `protobuf:"bytes,2,opt,name=ipfs" json:"ipfs,omitempty"`
	// Digest contains a digest-only reference (empty at the moment).
	Digest *StorageRefDigest `protobuf:"bytes,4,opt,name=digest" json:"digest,omitempty"`
	// InBand contains an in-band reference.
	InBand *StorageRefInBand `protobuf:"bytes,5,opt,name=in_band,json=inBand" json:"in_band,omitempty"`
}

func (m *StorageRef) Reset()                    { *m = StorageRef{} }
func (m *StorageRef) String() string            { return proto.CompactTextString(m) }
func (*StorageRef) ProtoMessage()               {}
func (*StorageRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StorageRef) GetStorageType() StorageType {
	if m != nil {
		return m.StorageType
	}
	return StorageType_StorageType_UNKNOWN
}

func (m *StorageRef) GetObjectDigest() []byte {
	if m != nil {
		return m.ObjectDigest
	}
	return nil
}

func (m *StorageRef) GetIpfs() *StorageRefIPFS {
	if m != nil {
		return m.Ipfs
	}
	return nil
}

func (m *StorageRef) GetDigest() *StorageRefDigest {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *StorageRef) GetInBand() *StorageRefInBand {
	if m != nil {
		return m.InBand
	}
	return nil
}

// StorageRefIPFS references an object in IPFS.
type StorageRefIPFS struct {
	// Reference contains the referenced multihash in string form.
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
	// IpfsRefType indicates the type of IPFS reference type this is.
	IpfsRefType IPFSRefType `protobuf:"varint,2,opt,name=ipfs_ref_type,json=ipfsRefType,enum=storageref.IPFSRefType" json:"ipfs_ref_type,omitempty"`
}

func (m *StorageRefIPFS) Reset()                    { *m = StorageRefIPFS{} }
func (m *StorageRefIPFS) String() string            { return proto.CompactTextString(m) }
func (*StorageRefIPFS) ProtoMessage()               {}
func (*StorageRefIPFS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StorageRefIPFS) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *StorageRefIPFS) GetIpfsRefType() IPFSRefType {
	if m != nil {
		return m.IpfsRefType
	}
	return IPFSRefType_IPFSRefType_BLOCK
}

// StorageRefDigest references an object by digest only.
type StorageRefDigest struct {
}

func (m *StorageRefDigest) Reset()                    { *m = StorageRefDigest{} }
func (m *StorageRefDigest) String() string            { return proto.CompactTextString(m) }
func (*StorageRefDigest) ProtoMessage()               {}
func (*StorageRefDigest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// StorageRefInBand references an object stored in-band.
type StorageRefInBand struct {
	// Data is the encoded object.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *StorageRefInBand) Reset()                    { *m = StorageRefInBand{} }
func (m *StorageRefInBand) String() string            { return proto.CompactTextString(m) }
func (*StorageRefInBand) ProtoMessage()               {}
func (*StorageRefInBand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StorageRefInBand) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageRef)(nil), "storageref.StorageRef")
	proto.RegisterType((*StorageRefIPFS)(nil), "storageref.StorageRefIPFS")
	proto.RegisterType((*StorageRefDigest)(nil), "storageref.StorageRefDigest")
	proto.RegisterType((*StorageRefInBand)(nil), "storageref.StorageRefInBand")
	proto.RegisterEnum("storageref.StorageType", StorageType_name, StorageType_value)
	proto.RegisterEnum("storageref.IPFSRefType", IPFSRefType_name, IPFSRefType_value)
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/storageref/storageref.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x8f, 0x9a, 0x40,
	0x14, 0xc5, 0x05, 0xad, 0x8d, 0x17, 0x34, 0xf4, 0xf6, 0x8f, 0xa4, 0xf1, 0xc1, 0xd0, 0xa4, 0x31,
	0x3e, 0x60, 0x62, 0xdb, 0x34, 0x69, 0xfb, 0x52, 0xd4, 0x36, 0xd4, 0x06, 0x9b, 0xd1, 0xa6, 0x8f,
	0x84, 0x3f, 0x83, 0xa5, 0xdd, 0x05, 0x32, 0x8c, 0x0f, 0x7e, 0x85, 0xfd, 0xd4, 0x1b, 0x06, 0xb2,
	0xce, 0xba, 0x66, 0x9f, 0x98, 0xf3, 0x9b, 0x7b, 0x0f, 0xe7, 0x5e, 0x80, 0x8f, 0xfb, 0x94, 0xff,
	0x3d, 0x84, 0x76, 0x94, 0x5f, 0xcf, 0x82, 0x82, 0x32, 0x7e, 0x60, 0x94, 0xe5, 0x61, 0xce, 0xd3,
	0xa8, 0x9c, 0x95, 0x3c, 0x67, 0xc1, 0x9e, 0x32, 0x9a, 0x48, 0x47, 0xbb, 0x60, 0x39, 0xcf, 0x11,
	0x4e, 0xc4, 0xba, 0x51, 0x01, 0xb6, 0xb5, 0x24, 0x34, 0xc1, 0x4f, 0xa0, 0x37, 0x97, 0x3e, 0x3f,
	0x16, 0xd4, 0x54, 0xc6, 0xca, 0x64, 0x30, 0x1f, 0xda, 0x92, 0x47, 0x53, 0xbd, 0x3b, 0x16, 0x94,
	0x68, 0xe5, 0x49, 0xe0, 0x1b, 0xe8, 0xe7, 0xe1, 0x3f, 0x1a, 0x71, 0x3f, 0x4e, 0xf7, 0xb4, 0xe4,
	0x66, 0x7b, 0xac, 0x4c, 0x74, 0xa2, 0xd7, 0x70, 0x29, 0x18, 0xda, 0xd0, 0x49, 0x8b, 0xa4, 0x34,
	0xd5, 0xb1, 0x32, 0xd1, 0xe6, 0xaf, 0x2f, 0x18, 0x13, 0x9a, 0xb8, 0xbf, 0xbe, 0x6d, 0x89, 0xa8,
	0xc3, 0xf7, 0xd0, 0x6d, 0xdc, 0x3a, 0xa2, 0x63, 0x74, 0xb9, 0xa3, 0x76, 0x27, 0x4d, 0x2d, 0x7e,
	0x80, 0xa7, 0x69, 0xe6, 0x87, 0x41, 0x16, 0x9b, 0x4f, 0x1e, 0x6b, 0x73, 0x33, 0x27, 0xc8, 0x62,
	0xd2, 0x4d, 0xc5, 0xd3, 0xfa, 0x0f, 0x83, 0xfb, 0x21, 0x70, 0x04, 0x3d, 0x46, 0x13, 0xca, 0x68,
	0x16, 0xd5, 0xcb, 0xe8, 0x91, 0x13, 0xc0, 0xcf, 0xd0, 0xaf, 0x42, 0xfa, 0x8c, 0x26, 0xf5, 0xba,
	0xd4, 0x87, 0xeb, 0x12, 0xb3, 0xd0, 0xa4, 0x5e, 0x57, 0x55, 0xdd, 0x08, 0x0b, 0xc1, 0x38, 0xcf,
	0x6f, 0xbd, 0x95, 0x59, 0x1d, 0x0e, 0x11, 0x3a, 0x71, 0xc0, 0x03, 0xf1, 0x76, 0x9d, 0x88, 0xf3,
	0xf4, 0x0a, 0x34, 0xe9, 0x33, 0xe0, 0x10, 0x9e, 0x4b, 0xd2, 0xff, 0xed, 0xad, 0xbd, 0xcd, 0x1f,
	0xcf, 0x68, 0xe1, 0x8b, 0x3b, 0x3f, 0x71, 0x51, 0x65, 0x31, 0x14, 0x7c, 0x05, 0x28, 0xd3, 0xa5,
	0xfb, 0x7d, 0xb5, 0xdd, 0x19, 0xea, 0x39, 0x77, 0x3d, 0xe7, 0xab, 0xb7, 0x34, 0xda, 0xd3, 0x2f,
	0xa0, 0x49, 0x53, 0xe0, 0x4b, 0x78, 0x26, 0x49, 0xdf, 0xf9, 0xb9, 0x59, 0xac, 0x8d, 0x56, 0xd5,
	0x2d, 0xe3, 0x8d, 0xf3, 0x63, 0xb5, 0xd8, 0x19, 0x4a, 0xd8, 0x15, 0x3f, 0xdd, 0xbb, 0xdb, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9c, 0xeb, 0x38, 0x0c, 0xaf, 0x02, 0x00, 0x00,
}
