// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/storageref/storageref.proto

/*
Package storageref is a generated protocol buffer package.

It is generated from these files:
	github.com/aperturerobotics/storageref/storageref.proto

It has these top-level messages:
	StorageRef
	StorageRefIPFS
*/
package storageref

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StorageType contains the possible types of storage.
type StorageType int32

const (
	// StorageType_UNKNOWN holds unknown values.
	StorageType_StorageType_UNKNOWN StorageType = 0
	// StorageType_IPFS is the IPFS storage type.
	StorageType_StorageType_IPFS StorageType = 1
)

var StorageType_name = map[int32]string{
	0: "StorageType_UNKNOWN",
	1: "StorageType_IPFS",
}
var StorageType_value = map[string]int32{
	"StorageType_UNKNOWN": 0,
	"StorageType_IPFS":    1,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}
func (StorageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// StorageRef references storage.
type StorageRef struct {
	// StorageType contains the type of storage this references.
	StorageType StorageType `protobuf:"varint,1,opt,name=storage_type,json=storageType,enum=storageref.StorageType" json:"storage_type,omitempty"`
	// ObjectDigest contains the digest of the decrypted object.
	// Optional.
	ObjectDigest []byte `protobuf:"bytes,3,opt,name=object_digest,json=objectDigest,proto3" json:"object_digest,omitempty"`
	// Ipfs contains a IPFS storage reference.
	Ipfs *StorageRefIPFS `protobuf:"bytes,2,opt,name=ipfs" json:"ipfs,omitempty"`
}

func (m *StorageRef) Reset()                    { *m = StorageRef{} }
func (m *StorageRef) String() string            { return proto.CompactTextString(m) }
func (*StorageRef) ProtoMessage()               {}
func (*StorageRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StorageRef) GetStorageType() StorageType {
	if m != nil {
		return m.StorageType
	}
	return StorageType_StorageType_UNKNOWN
}

func (m *StorageRef) GetObjectDigest() []byte {
	if m != nil {
		return m.ObjectDigest
	}
	return nil
}

func (m *StorageRef) GetIpfs() *StorageRefIPFS {
	if m != nil {
		return m.Ipfs
	}
	return nil
}

// StorageRefIPFS references an object in IPFS.
type StorageRefIPFS struct {
	// ObjectHash contains the referenced object hash in string form.
	ObjectHash string `protobuf:"bytes,1,opt,name=object_hash,json=objectHash" json:"object_hash,omitempty"`
}

func (m *StorageRefIPFS) Reset()                    { *m = StorageRefIPFS{} }
func (m *StorageRefIPFS) String() string            { return proto.CompactTextString(m) }
func (*StorageRefIPFS) ProtoMessage()               {}
func (*StorageRefIPFS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StorageRefIPFS) GetObjectHash() string {
	if m != nil {
		return m.ObjectHash
	}
	return ""
}

func init() {
	proto.RegisterType((*StorageRef)(nil), "storageref.StorageRef")
	proto.RegisterType((*StorageRefIPFS)(nil), "storageref.StorageRefIPFS")
	proto.RegisterEnum("storageref.StorageType", StorageType_name, StorageType_value)
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/storageref/storageref.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x8d, 0x8a, 0xe0, 0x6b, 0x5d, 0x4a, 0x14, 0xb6, 0x78, 0xb1, 0xac, 0x97, 0xe2, 0xa1,
	0x8b, 0xeb, 0x41, 0x10, 0x8f, 0x22, 0x8a, 0x50, 0x25, 0xab, 0x78, 0x2c, 0x6d, 0x7d, 0x6d, 0x22,
	0x48, 0x42, 0xf2, 0xf6, 0xb0, 0x3f, 0xc6, 0xff, 0x2a, 0xa6, 0x85, 0x46, 0xf0, 0x96, 0xf9, 0x66,
	0x98, 0x0c, 0x0f, 0xae, 0x7b, 0x45, 0x72, 0xd3, 0x14, 0xad, 0xfe, 0x5a, 0xd6, 0x06, 0x2d, 0x6d,
	0x2c, 0x5a, 0xdd, 0x68, 0x52, 0xad, 0x5b, 0x3a, 0xd2, 0xb6, 0xee, 0xd1, 0x62, 0x17, 0x3c, 0x0b,
	0x63, 0x35, 0x69, 0x0e, 0x13, 0x59, 0x7c, 0x33, 0x80, 0xf5, 0x20, 0x05, 0x76, 0xfc, 0x06, 0xe2,
	0xd1, 0xac, 0x68, 0x6b, 0x30, 0x65, 0x19, 0xcb, 0x67, 0xab, 0x79, 0x11, 0x74, 0x8c, 0xe9, 0xd7,
	0xad, 0x41, 0x11, 0xb9, 0x49, 0xf0, 0x73, 0x38, 0xd2, 0xcd, 0x27, 0xb6, 0x54, 0x7d, 0xa8, 0x1e,
	0x1d, 0xa5, 0x7b, 0x19, 0xcb, 0x63, 0x11, 0x0f, 0xf0, 0xce, 0x33, 0x5e, 0xc0, 0xbe, 0x32, 0x9d,
	0x4b, 0x77, 0x33, 0x96, 0x47, 0xab, 0xd3, 0x7f, 0x8a, 0x05, 0x76, 0x8f, 0x2f, 0xf7, 0x6b, 0xe1,
	0x73, 0x8b, 0x4b, 0x98, 0xfd, 0xe5, 0xfc, 0x0c, 0xa2, 0xf1, 0x1b, 0x59, 0x3b, 0xe9, 0x17, 0x1e,
	0x0a, 0x18, 0xd0, 0x43, 0xed, 0xe4, 0xc5, 0x2d, 0x44, 0xc1, 0x46, 0x3e, 0x87, 0xe3, 0x40, 0x56,
	0x6f, 0xe5, 0x53, 0xf9, 0xfc, 0x5e, 0x26, 0x3b, 0xfc, 0x04, 0x92, 0xd0, 0xf8, 0x2d, 0x4f, 0x58,
	0x73, 0xe0, 0x6f, 0x74, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xd1, 0x35, 0xa1, 0x5e, 0x01,
	0x00, 0x00,
}
